spring:
  application:
    name: Student-Management-System
  datasource:
    url: jdbc:mysql://localhost:3306/student_database?createDatabaseIfNotExist=true
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true

super_admin:
  email: ${SUPER_ADMIN_EMAIL}











